### ISSUE TITLE
Check for unpadded addresses in byte32 fields that look like uint

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/multisig-ops#1008]
This tx sent 2000 USDC to the wrong place/lost.
https://app.onchainden.com/safes/eth:0xc38c5f97B34E175FFd35407fc91a937300E33860/transactions/0xc071bf4295bd0c77073357799395c3c842c6b8d7e194c49a8f87ebfd08e5921e?nid=349267

It looks a very lot like this tx which bridged USDC to the LM multisig on arbiturm:
https://app.onchainden.com/safes/eth:0xc38c5f97B34E175FFd35407fc91a937300E33860/transactions/0xc3667966871085231b3975bf803e0e151ddbfc922398fe7303c1b56b9ce80a29

The difference is where the 0 padding on the address is.  The errant TX was generated when someone put in an address into the bytes32 field, and safe padded the 0's on the wrong end automatically.

Check bytes32 inputs to see if they are eth addresses.  If so print a warning (unpadded address in bytes32 input) or something in the verification and/or report line.

**Comment by gosuto-inzasheru** [comment]
the report actually picked up on this: https://github.com/BalancerMaxis/multisig-ops/pull/1006#issuecomment-2142815757
