### ISSUE TITLE
add ARB rewards for weETH-wstETH, and ezETH-wstETH

### ISSUE THREAD

**Issue by frondoto** [BalancerMaxis/multisig-ops#1214]
boost contracts:
gyro weeth-wsteth: https://arbiscan.io/address/0x6B970F0D1F0255b8E0B1c4515Ae827931b32312C
ezeth-wsteth: https://arbiscan.io/address/0xfcF293AFa58fa277935eddAa44E0f782EC41B09B
2 weeks duration, ARB rewards.

**Comment by gosuto-inzasheru** [comment]
solved by #1216
