### ISSUE TITLE
Adjust Fee Setting on auraBAL and 80BAL-20WETH connector pool

### ISSUE THREAD

**Issue by Xeonus** [BalancerMaxis/multisig-ops#1270]
## Specification
We want to adjust fees on following pools:
- auraBAL:80BAL-20WETH to 0.05% from 0.3% 
(https://etherscan.io/address/0x3dd0843a028c86e0b760b1a76929d1c5ef93a2dd)
- 80BAL-20WETH:WETH  to 0.05% from 1% 
(https://etherscan.io/address/0xc5c91aea7551095c3e1ff0f94f682c45b347ad73)

## How to execute
The LM multisig is permissioned to set swap fees on pools. Therefore, simply call setSwapFeePercentage on the pool contracts from the LM Multisig, see [nonce 311](https://etherscan.io/tx/0x468a03e46c66726e001e47b24a6706e41b16a19b01fe0d9206e65837ecd44f4c) as example

To set a pool to 0.05%, set uint256 to `500000000000000`

**Comment by Tritium-VLK** [comment]
see #1277

**Comment by gosuto-inzasheru** [comment]
> Xeonus
> Yes, can be closed. After discussing with Maha we said to leave auraBAL pool as is
