### ISSUE TITLE
give emergency msig necessary perms on vault v3

### ISSUE THREAD

**Issue by gosuto-inzasheru** [BalancerMaxis/multisig-ops#1500]
current (v2!) relevant perms for emergency msig are:

- [ ] `ProtocolFeeCollector.denylistToken `
- [ ] `PoolFactory.disable`
- [ ] `Pool.disableRecoveryMode`
- [ ] `Pool.enableRecoveryMode`
- [ ] `Pool.pause`
- [ ] `Pool.unpause`

ref: https://docs.balancer.fi/reference/authorizer/mainnet.html

**Comment by gosuto-inzasheru** [comment]
for v3 i found these permissions to be analogous:

- `VaultAdmin.pauseVault()`
- `VaultAdmin.unpauseVault()`
- `VaultAdmin.pausePool(pool)`
- `VaultAdmin.unpausePool(pool)`
- `VaultAdmin.enableRecoveryMode(pool)`
- `VaultAdmin.disableRecoveryMode(pool)`
- `VaultAdmin.pauseVaultBuffers()`
- `VaultAdmin.unpauseVaultBuffers()`
- `BasePoolFactory.disable()` how to reenable??
- `ProtocolFeeController` no denylist anymore??

**Comment by danielmkm** [comment]
- Once disabled, the factory cannot be re-enabled.
- I'm asking for clarification on the exclusion of a token denylist on the fee controller

Additional emergency permissions:
- `Vault.disableQuery`
- `Vault.enableQuery`
- `Vault.disableQueryPermanently`
