### ISSUE TITLE
docs: make sure v3 permissions are updated automatically

### ISSUE THREAD

**Issue by gosuto-inzasheru** [BalancerMaxis/multisig-ops#1501]
ref: https://docs-v3.balancer.fi/developer-reference/authorizer/

**Comment by Xeonus** [comment]
For v3 docs what we need to do is not use github actions but simply cross-reference permissions and reverse lookups and create the table in js / vue on the fly in the docs page.

https://github.com/BalancerMaxis/bal_addresses/tree/main/outputs/permissions/active
https://github.com/BalancerMaxis/bal_addresses/blob/main/outputs/arbitrum_reverse.json

**Comment by Xeonus** [comment]
Also [tracked in docs repo](https://github.com/balancer/docs-v3/issues/185)
