### ISSUE TITLE
Script to merge a directory of payload jsons

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/multisig-ops#204]
The multsig want's PR jsons batched.  I offered @SHAKOTN 100 BAL to write it.  It is now in operation.

@SHAKOTN please provide payment address here.

**Comment by SHAKOTN** [comment]
Please send to this address `0x581fb162b8fa2eb6f0273c2086cb5dd865f7b338`

Thanks! cc @Tritium-VLK

**Comment by Tritium-VLK** [comment]
https://etherscan.io/tx/0x8949c144fce0eb2e11b8ad9a3313df2fae59eada4730033fe952794d810c37c7
