### ISSUE TITLE
Bounty:  Maxi Gas Spend Dune Dashboard

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/multisig-ops#206]
# Intro
The [Maxi Gas Station](https://github.com/BalancerMaxis/multisig-ops/blob/main/docs/upkeeps/maxiGasStation.md), deployed at [0x2f1901f2a82fcc3ee9010b809938816b3b06fa6a](https://etherscan.io/address/0x2f1901f2a82fcc3ee9010b809938816b3b06fa6a) receives eth from the [Maxi Ops Multisig](https://etherscan.io/address/0x166f54F44F271407f24AA1BE415a730035637325) and pays it out to [Maxi Deployers](https://github.com/BalancerMaxis/bal_addresses/blob/f1635a3cc78ccb7cd9f9ef4d2242e393b9f7ef32/extras/signers.json#L19) when they are running low.

Some deployers may also have a signer address where they send eth onward to.

We need a report about what is happening to this eth. Note that the amount of BAL for each bounty will depend on how sexy the Maxi's think your Dashboard is. Did you do the very least and show some tables, or did you find nice ways to represent the data that help people understand where the DAO gas is going?

# Scope and Pay
Basic Dash (25-75 BAL):

- Track all ETH transfers from the gas station and from any address it sends ETH to.
- Show spend per gas-station recipient
- Show onward sending of ETH and spend per subwallet (going a few layers deep if possible would be cool but shouldn't be necessary)
- Map all possible addresses to names, you can look up the names by address here: https://github.com/BalancerMaxis/bal_addresses/blob/main/outputs/mainnet_reverse.json

Advanced Dash (+25-100BAL):

Show how the eth was spent:

- Maxi's create pools from factories
- Maxi's do operations on the vault, and linear pools
- Maxi's might sometimes swap a little gas money for link or a test token (hopefully not too much)
- Maxi's execute lots of mutlsig transactions
- Breaking down multisig tx spend by type is super interesting. Big gas spend and/or frequent tx's include [Posting voting incentives](https://etherscan.io/tx/0x483d7988e32b885699ec9b6b3d2e30b5f7cdf9406d9f4dd05d7aab6cccb0cc51)
 
Show info about the chainlink automation status:
- How much link is there at the moment?
- Link spend over time
- anything else that looks cool?

# Engagement Details
This bounty will be assigned to one person at a time to try to complete it.  It is expected that meaningful results are delivered each week, or else the assignment may move to someone else.  The Basic Dash amount will be paid out once the Basic Dash is completed and deemed acceptable by the Maxis.  Same with Advanced.

If you would like to do this bounty and request a lock, please comment on this issue and DM Tritium on the Balancer Discord to discuss.  Once assigned, the assigned tag will be added until the bounty is finished, or sufficient time has elapsed without demonstrated progress.  We do not expect this to take more than a week or two to complete in full

**Comment by LeviScoffie** [comment]
Hi @Tritium-VLK , I would like to do this bounty. I've been a dune wizard for close to an year now . The requirements for the basic dash and advanced dash are all within reach of achievement

**Comment by Tritium-VLK** [comment]
> Hi @Tritium-VLK , I would like to do this bounty. I've been a dune wizard for close to an year now . The requirements for the basic dash and advanced dash are all within reach of achievement

Ok.  I marked this assigned to give you some time to submit something.  Thanks for your interest and looking forward to seeing what comes out :)

**Comment by LeviScoffie** [comment]
@Tritium-VLK  A week from now right, I should have something. Right?

**Comment by LeviScoffie** [comment]
Hey @Tritium-VLK . This is the submission for the Basic Dash scope. If there needs any clarifications, I'll more that happy to clarify. 
[Basic Dash](https://dune.com/scoffie/maxigasstation?undefined=)

**Comment by LeviScoffie** [comment]
**Brief Overview:**

- This dashboard tracks all ETH transfers from the gas station.

- Also, it tracks ETH transfers out from the addresses the gas station send the ETH to.

- The address labels are derived from the [LINK](https://github.com/BalancerMaxis/bal_addresses/blob/main/outputs/mainnet_reverse.json) whereas those address names that are missing are derived from Dune's eth.contracts decoded tables.

- You can select a specific Maxi Deployer and get to view their specific eth receiving and spending transactions over the time period the Gas Station contract has been up.

**Comment by LeviScoffie** [comment]
Great. 
Sure here's the payment address [0xac0B4859EF86241d32A6A39540b34d65e9Ee7d9]()

**Comment by Tritium-VLK** [comment]
@LeviScoffie https://etherscan.io/tx/0xea6d5d3f2836ceb6ec2758e7b5f543c7f879be223a4d6f8fb43a8ea48f27b085

**Comment by LeviScoffie** [comment]
@Tritium-VLK  Thanks. Well Received ser

**Comment by LeviScoffie** [comment]
Hey all This is the submission for the Advanced Dash scope. If there needs any clarifications, I'll be more than happy to clarify.
[Advanced Dash](https://dune.com/scoffie/advancedmaxigasstation).

**Comment by LeviScoffie** [comment]
**Brief Overview**

- This dashboard tracks signers deployed by the Maxis which perform the duties on behalf of the original deployer address that get fed gas from the GasStation.
- Tracks gas money that has been swapped for LINK to feed GasStation that performs upkeeps or swapped for  other test tokens.
- Tracks all pools created by the Maxis and average spend of gas on the actions.
- Tracks the actions performed in the Vault, which include batchswaps, joining pools, exiting pools as well as swapping routes that use other protocol smart contracts.
- Tracks all the multisig operations and the spend by the Maxis to execute various transactions.
- Finally, it tracks the balance left in the GasStation, along with its balances over time. Moreover, it shows the LINK used by the registry addresses and how it has been funded.
-

**Comment by Tritium-VLK** [comment]
Maxis have agreed that @LeviScoffie has done a bang up job on the advanced dash.  Please pay 100 BAL to 0xac0B4859EF86241d32A6A39540b34d65e9Ee7d96
