### ISSUE TITLE
External Review:  ChildChainGaugeInjector

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/multisig-ops#244]
https://balancerecosystem.slack.com/archives/C01NZJFFPBM/p1685549840223129

Review Request:
We currently execute a growing number of time sensitive multisig transactions each week to pay non-bal emissions into gauges on child chains for DAOs that request it.
The number of these instances is likely to grow quickly over the next month or two as the bribe market saturates and with the rollout of new chains, and the Arbi incentive program from our airdrop.
Mike and I have written the following smart contract/repo which is a chainlink keeper that automates this process based on admin defined schedules.
https://github.com/BalancerMaxis/ChildChainGaugeInjectoooor
The project was written in brownie, but there is a complete readme with setup notes and information about how it would be used.
We are considering building a factory to allow these to be easily launched by daos/per token but it's not important for now.
It would be super amazing if we could start working with these in prod in the next 2-3 weeks as the number of direct injection situations is likely to really pick up steam.
[@Mike B](https://balancerecosystem.slack.com/team/U02F8LBPG05)
 and I are always available to answer any questions or chat about the code.
:face_in_clouds:
1
:+1:
1

**Comment by rabmarut** [comment]
The Integrations Team will target this Friday, June 9, to complete this review. In the event that we need more time, I will post an update here as soon as possible.

**Comment by rabmarut** [comment]
Hi @Tritium-VLK, please refrain from deploying this contract. We have identified some issues.

We need a bit more time to compile the full report. We will reexamine our findings with fresh eyes on Monday, and we'll plan to send you the report by Tuesday.

**Comment by rabmarut** [comment]
Hi @Tritium-VLK, please find our full report [here](https://quark-ceres-740.notion.site/ChildChainGaugeInjector-8d1b5ab8e0864f1190b1a3704aee6b1d?pvs=4). This was generated by @gerrrg and myself. Note that we have deemed this contract **unsuitable for deployment** until at least the three high-severity issues can be addressed.

Notably, the contract operates on the wrong set of gauges if any of the listed gauges is not ready at the time of execution. It also provides avenues for passing an incorrect list of gauges to be executed on and neglects to validate the input list.

**Comment by Tritium-VLK** [comment]
See here for a PR and review notes in response to this review.  And thanks again for your time/eyes/wisdom.

https://github.com/BalancerMaxis/ChildChainGaugeInjectoooor/pull/6
