### ISSUE TITLE
External Review:  veBalFeeInjector

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/multisig-ops#245]
The Maxis currently pay fees into the veBalFee distributor in the form of bb-a-usd and BAL rendered from collecting and selling our fees.

Fee processing is handled on a biweekly basis to align with the 2 week voting epochs (aura).  As a result, each week there are 2 weeks of fees left over that must be paid in over 2 separate payments.

The  Maxi's have a long list of these kinds of regular operations and are prone to forgetting things as they stack up.  We also shouldn't have to sign every week to keep the fees flowing.

The veBalFeeInjector is meant to receive the proceeds from each fee processing round and pay it out over 2 chunks.

@mkflow27 has already done some initial review after we started working on it together.  The need for these reviews hit right at the same time as governance around orb kicked into steam, so this just seemed a way to focus on work getting done.  I guess it created problems sorry.

The net result is that this contract has been waiting for review for a rather long time, and has had a lot of eyes on it.  Would just like a stamp of approval before deploying it.

The repo can be found here, complete with a readme and some tests written in brownie by myself, and in foundry by @mkflow27 

https://github.com/BalancerMaxis/veBalFeeInjector

**Comment by rabmarut** [comment]
The Integrations Team will target this Friday, June 9, to complete this review. In the event that we need more time, I will post an update here as soon as possible.

**Comment by rabmarut** [comment]
@Tritium-VLK 

Thanks to @mkflow27 for the majority of this review. I've also given it a quick pass. **The code should function as intended**, and at the very least there are avenues for recovering funds if ever the contract should enter an undesirable state. All findings are purely informational.

https://quark-ceres-740.notion.site/veBalFeesInjector-b20ab45d393e4daf9edc0e8c31cf50ae?pvs=4
