### ISSUE TITLE
Revised LZ rate provider

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/multisig-ops#272]
Scope details from @markusbkoch:
Hey guys. Like I've said in internal chats, I think it's probably fine to start experimenting with specialized contracts like the ones witherblock has developed.

But Balancer pools require that rate providers implement IRateProvider (https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/interfaces/contracts/pool-utils/IRateProvider.sol). So I think it's safe to assume that any rate that we'll ever care about will be queriable via getRate(). Which means we can build a more generalized architecture.

For clarity and disambiguation I'll define a few terms
- OriginalRateProvider: any contract that implements IRateProvider
- Sender: a contract that interacts with the LZ endpoint to send the return of any RateProvider's getRate() on the same network to a Receiver in another network
- Receiver: a contract that receives the information from the Sender and stores it in a srcChainId => OriginalRateProviderAddress => _rate mapping
- ChildChainRateProvider: a contract that implements IRateProvider and reads the latest rate stored in Receiver for a specific srcChainId and OriginalRateProvider
- ChildChainRateProviderFactory: a contract that deploys ChildChainRateProviders (ie. create(srcChainId, OriginalRateProviderAddress)) 

Notice that the notion of mainnets and L2s is irrelevant to these definitions. We could have a OriginalRateProvider and Sender on Polygon and it's Receiver and ChildChainRateProvider on Polygon zkEVM or even Mainnet. The ChildChainRateProvider is the only contract our pools would read from, and they'd be configured to read from the relevant srcChainId/OriginalRateProviderAddress.

In addition to sending/receiving/storing the rate, I think it could be useful to also send/receive/store the srcChain timestamp at which the information was sent, so that it's easier to build monitoring systems on top of this.

What do you guys think?

Additional thoughts from Tritium:
Hey just one other thought, but these rates don't change fast and we're talking about daily updates.  Would it make sense to have a configurable timelock/delay.
So for example the receiver waits timeDelaySeconds after receiving the rate before reporting it?  This would give the chance to monitor for a problematic change and try to somehow get in front of it/save the funds.  Does that make sense?

**Comment by markusbkoch** [comment]
>So for example the receiver waits timeDelaySeconds after receiving the rate before reporting it? This would give the chance to monitor for a problematic change and try to somehow get in front of it/save the funds. 

That's an interesting idea but still requires some form of admin control over the receiver to set the delay and enable the "get in front of it" part, since the pools can't be paused. For example, a permissioned function on the `ChildChainRateProvider` that allowed the emergency subDAO to set a different source for the rate. But then LPs would be trusting the subDAO, and there's also the question of what do we switch over to. At that point then maybe it makes more sense to just have the subDAO post the rates every day, or something like MakerDAO's early days medianizer.

**Comment by Tritium-VLK** [comment]
WIP scope doc in collaboration with Uma:
https://docs.google.com/document/d/15QI9p7IirBioUgqg-1yWrkXi4ndlN1JIxB6UBC2J3NE/edit

Swell has expressed some interest in exploring/implementing this concept for their crosschain push.

**Comment by Tritium-VLK** [comment]
Current rate provider code:

https://github.com/witherblock/gyarados
