### ISSUE TITLE
Integrate BIP numbers into multisig payloads and reporting

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/multisig-ops#295]
**Story:**
As a dev multisigner, I'd rather get a nice Jupiter notebook that lays out everything to sign, and has an easy way to grok that automated checks have passed.  I'd like Mike's final review to somehow be linkable to items on it.  I'm busy, I don't want get lost in details, but would maybe sometimes want to drill down.

**Approach:**
- Require BIP_NUMBER be included into the global settings of every payload in BIPs.  
- Validate that it is set, and in any line item reports (gauge adds/kills) include the bip number (consider if we even need the filename anymore/how critical this is, probably gud to keep) in the individual payload reporting and validation.
- Update merge script to copy BIP_NUMBER defined globally in each file, into each individual transaction.
- Design fancy merge report for multisigners.

Transactions grouped by BIP
- Little checkboxes to show all the validations that passed.
- Link to output of individual payload reports (I think we make a text file in the repo)
- Talk to @mikebmikeb about how to incorporate his final review.
- Talk to solar about how to make the report maximally sexy for the audience (he understands them/this best)

Check in lots to make sure this continues to make sense.  Ask other maxis for feedback before you get in to deep.

**Comment by Tritium-VLK** [comment]
Example of current "report":

Solar announcing payloads:

Solar announcing the loadening:
<img width="499" alt="image" src="https://github.com/BalancerMaxis/multisig-ops/assets/11885129/39db583b-9955-44c0-b986-92bbadb10fcc">


Mike reporting on what it does(iz long but this is enough to get the point):
<img width="510" alt="image" src="https://github.com/BalancerMaxis/multisig-ops/assets/11885129/312bdb21-7bcc-4d8e-bb6d-eee927ac4075">

**Comment by SHAKOTN** [comment]
Note to myself:
@Tritium-VLK wants to take the BIP number(it's in payload, validate). Every tx should have a BIP number in merge report

**Comment by Tritium-VLK** [comment]
Wouldn't hurt to include it in the individual reports either.

**Comment by Tritium-VLK** [comment]
#324
