### ISSUE TITLE
Pay shak 600 BAL

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/multisig-ops#313]
For various bounty work in June we have agreed to pay @SHAKOTN 600 BAL via is company to address:

`0x7bd6e8874d668813ab93da6c1a6334c6c2c84a2f`

**Comment by 0xDanko** [comment]
https://etherscan.io/tx/0x89b2029587454bed7a8264d6224daeb819d7298534642cb93124b53fe2299c14
