### ISSUE TITLE
Token designs for L2 deployments

### ISSUE THREAD

**Issue by 0xDanko** [BalancerMaxis/multisig-ops#389]
### Intro

With the recent L2 deployments, specially with Balancer native products likethe Boosted Pools, there are token images graphics missing on the UI. We need a designer from the Balancer community to work on these tokens, considering Balancer's style and previous designs, but also respecting the brands these tokens are associated with (i.e. waUSDC relates to Aave and Circle's USDC branding).

### Specification

- PNG files for each token;
- 200x200 pxl;
- transparent background.

**Batch n.1** |   |   |  
-- | -- | -- | --
Token | Chain | Ref pool | Ref project
waWMATIC | Polygon PoS | https://app.balancer.fi/#/polygon/pool/0xe78b25c06db117fdf8f98583cdaaa6c92b79e917000000000000000000000b2b | Aave
bb-a-WMATIC | Polygon PoS | https://app.balancer.fi/#/polygon/pool/0xe78b25c06db117fdf8f98583cdaaa6c92b79e917000000000000000000000b2b | Aave
waDAI | Polygon PoS | https://app.balancer.fi/#/polygon/pool/0xb371aa09f5a110ab69b39a84b5469d29f9b22b76000000000000000000000b37 | Aave
waUSDC | Polygon PoS | https://app.balancer.fi/#/polygon/pool/0xb371aa09f5a110ab69b39a84b5469d29f9b22b76000000000000000000000b37 | Aave
waUSDT | Polygon PoS | https://app.balancer.fi/#/polygon/pool/0xb371aa09f5a110ab69b39a84b5469d29f9b22b76000000000000000000000b37 | Aave
bb-a-WAVAX | Avalanche | tbd | Aave
waWAVAX | Avalanche | tbd | Aave

**Batch n.2** |   |   |  
-- | -- | -- | --
Token | Chain | Ref pool | Ref project
cagWXDAI | Gnosis | https://app.balancer.fi/#/gnosis-chain/pool/0xfedb19ec000d38d92af4b21436870f115db22725000000000000000000000010 | Agave
cagUSDT | Gnosis | https://app.balancer.fi/#/gnosis-chain/pool/0xfedb19ec000d38d92af4b21436870f115db22725000000000000000000000010 | Agave
cagUSDC | Gnosis | https://app.balancer.fi/#/gnosis-chain/pool/0xfedb19ec000d38d92af4b21436870f115db22725000000000000000000000010 | Agave
bb-o-USD | Polygon zkEVM | https://app.balancer.fi/#/zkevm/pool/0xe274c9deb6ed34cfe4130f8d0a8a948dea5bb28600000000000000000000000d | Ovix
bb-o-USDT | Polygon zkEVM | https://app.balancer.fi/#/zkevm/pool/0xe274c9deb6ed34cfe4130f8d0a8a948dea5bb28600000000000000000000000d | Ovix
bb-o-USDC | Polygon zkEVM | https://app.balancer.fi/#/zkevm/pool/0xe274c9deb6ed34cfe4130f8d0a8a948dea5bb28600000000000000000000000d | Ovix
woUSDC | Polygon zkEVM | https://app.balancer.fi/#/zkevm/pool/0xe274c9deb6ed34cfe4130f8d0a8a948dea5bb28600000000000000000000000d | Ovix
woUSDT | Polygon zkEVM | https://app.balancer.fi/#/zkevm/pool/0xe274c9deb6ed34cfe4130f8d0a8a948dea5bb28600000000000000000000000d | Ovix
tUSDT | Polygon PoS | https://app.balancer.fi/#/polygon/pool/0xb3d658d5b95bf04e2932370dd1ff976fe18dd66a000000000000000000000ace | Tetu
tUSDC | Polygon PoS | https://app.balancer.fi/#/polygon/pool/0xb3d658d5b95bf04e2932370dd1ff976fe18dd66a000000000000000000000ace | Tetu
tDAI | Polygon PoS | https://app.balancer.fi/#/polygon/pool/0xb3d658d5b95bf04e2932370dd1ff976fe18dd66a000000000000000000000ace | Tetu

</body>
</html>

### Engagement Details
- The batches will be assigned to one person at a time to try to complete it;
- It is expected that the results are delivered within a week, or else the assignment may move to someone else;
- Each payment will be due after the final approval (completed and deemed acceptable by the Maxis) of each batch;
- We do not expect this to take more than a week or two to complete in full.
- Assignee must provide a valid Ethereum mainnet wallet for payment transfer 
Batch n.1 **70 USDC**
Batch n.2: **110 USDC**

If you would like to do this bounty and request a lock, please comment on this issue and/or tag Danko or Zekraken on the Balancer Discord to discuss. Once assigned, the "Assigned" tag will be added until the bounty is finished, or sufficient time has elapsed without demonstrated progress.

**Comment by 0xDanko** [comment]
Feel free to reach out to me about this designs. There's a certain standard if you look at previous boosted pools tokens on mainnet, so pretty easy to follow. If anyone can grind on the weekend, Avax tokens are the ones we wanted first! :)

**Comment by timbalabuch** [comment]
I'm on it!

**Comment by timbalabuch** [comment]
[Token designs for L2 deployments-389 - transparent BG -V3.zip](https://github.com/BalancerMaxis/multisig-ops/files/12164276/Token.designs.for.L2.deployments-389.-.transparent.BG.-V3.zip)

![Token designs for L2 deployments #389](https://github.com/BalancerMaxis/multisig-ops/assets/24606512/60d605a6-3a10-40ac-a4b9-01431887d619)

**Comment by 0xDanko** [comment]
https://etherscan.io/tx/0x984429371d75802fdb167fe448c87e88a4fa6c23af04e080760669eae07f4cf6
