### ISSUE TITLE
Script to generate Arb Payouts per Pool for  proposed incentives program

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/multisig-ops#392]
Full grant application is here: 

https://docs.google.com/document/d/15Him_MjKv8Y0_fg4NqPIBWMp5xTkqQPhv3247HKu21E/edit

The tech challenge is to figure out how to distribute arb.

Basic Rules:

97.704 ARB distributed per week (max)
No more than 10% ARB to any given pool
Arb distributed based on veBAL voting (relative % veBAL) with all rewards distributed each week based on ratios.
Fixed(constant) boost per pool of 1-2x
Dynamic fee based boost per pool of 1-3x

Fee based boost:

`[Fees earned/value of bal emitted + 1]`

Psuedocode: (for example)

- Pull all active arbitrum gauges from the subgraph and their current veBAL vote count.

For Each Gauge:
- Determine BAL emitted per pool by multiplying current vote by emissions defined by the [inflation schedule](https://docs.balancer.fi/concepts/governance/bal-token.html#supply-inflation-schedule) **121,929.98 BAL per Week this year**
-  Determine USD value of BAL emitted.
- Determine USD value of fees collected over the last week (just use whatever fee data there is/we can improve this later)
- Calculate the variable boost by dividing fees earned/bal emitted
- Add the variable and the fixed boost (guess we need a json of fixed boost per gauge) (note that the 1x shouldn't add)
- Multiple BAL emitted by boost

Final Allocation:
- Allocate 97k ARB to pools based on relative weight of post boosted voting results
- dump CSV or JSON with Gauge + amount + maybe total boost applied and/or more data is always gud.

**Comment by Tritium-VLK** [comment]
Docs on subgraph to do the gauge stuff: https://docs.balancer.fi/reference/subgraph/gauges/entities.html#gaugeshare

**Comment by SHAKOTN** [comment]
For myself: take protocol fee from Snapshot data and calculate BAL emissions per ARB pools and calculate stuff based on Trit's comment

**Comment by SHAKOTN** [comment]
Done here:
https://github.com/BalancerMaxis/data_automation/blob/main/notebooks/arb_distribution.ipynb
