### ISSUE TITLE
The Balancer Report and Discord mod

### ISSUE THREAD

**Issue by 0xDanko** [BalancerMaxis/multisig-ops#418]
### Introduction

The Balancer Report is a weekly newsletter written and built by the Balancer community. Historically, it's been authored and coauthored by several contributors, previously housed at [Substack](https://balancer.substack.com/archive), now living under the Balancer Protocol's [Medium ](https://medium.com/@balancer.ballers) account where all the current publications surrounding the ecosystem are currently being held.

> Get the latest news from Balancer every week straight to your inbox. We’ll be monitoring activity from liquidity providers, picking apart any interesting whale activities, diving deep into the latest degen farms, and keeping you up to date with everything happening in the Balancer ecosystem.

### Engagement Details

The Balancer Maxis currently is funding the continuation of this project, understanding it's an asset to the community that goes beyond the marketing outreach. The assigned community contributors (Ballers) to this bounty will deliver the weekly copywriting, stats and updates, along with the current Discord mod engagement for first level support of Balancer users in the server.
**Bounty:** 3.500 USDC/month - Q3/2023

- The bounty is assigned to Ballers on a quarterly basis;
- In case results are incomplete and/or deemed unacceptable by the Maxis it may move to someone else;
- Each payment will be due at the end of the month;
- Assignee must provide a valid Ethereum mainnet wallet for payment transfer

**Public disclosure:** if there's any interest from members of the community to pick up this bounty, please comment on this issue and/or tag Danko on the Balancer Discord to discuss onboarding the Balancer DAO.

**Comment by 101717** [comment]
0x9a0965916851cd6582a8a8cdb9a1c2a1614492d6


July reports done together with Cosme:

- [July 3](https://medium.com/balancer-protocol/the-balancer-report-how-well-do-you-really-know-balancer-7d90f3c734b6)  
- [July 10](https://medium.com/balancer-protocol/the-balancer-report-cross-chain-boosts-d40c5ce5275f) 
- [July 17](https://medium.com/balancer-protocol/the-balancer-report-the-three-part-symphony-beae45b7dc95) 
- [July 24](https://medium.com/balancer-protocol/the-balancer-report-the-wonders-of-concentrated-liquidity-3a078b57e96b)

**Comment by Cosme0x** [comment]
0xea81d2de2e5ec21a00a4446309651a2642ee9d8d

**Comment by 0xDanko** [comment]
https://etherscan.io/tx/0x984429371d75802fdb167fe448c87e88a4fa6c23af04e080760669eae07f4cf6

**Comment by 0xDanko** [comment]
https://etherscan.io/tx/0x812c5d47661761a0d998eec91a745686ed9f7705f59b58df134308c95f287f21

**Comment by 0xDanko** [comment]
https://etherscan.io/tx/0x2f71e1f4f7d5748893fca329845585c809def64b1607e1b9d9a760c53ed2afbe
