### ISSUE TITLE
Aurabal Vester contract for Maxi Pay

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/multisig-ops#535]
Maxis can elect to take a portion of their pay in vested auraBAL instead of USDC for a multipler.  This describes the vesting contract where the aurabal goes.  Noe that this could be a single contract, or perhaps better a factory that launches a contract per recipient address.

Plan is to run on Arbitrum

Features:
- Has a recipient and an owner (multisig of maxi ops + dao multi)
- Has a funder (maxi ops)
- Accepts auraBAL pounder tokens
- Deposit of tokens includes an unlock date, after which the pounder tokens can be withdrawn from the contract by the owner at any time.
- Pounder tokens accumulate Aura to claim.  The recipient should be able to claim this aura to their wallet at any time.
- Deposits may be made on a regular basis, sometimes with overlapping lock dates 
    - for example lets say someone gets 3k auraBAL a month for q1 2024 and q2-204
      - 3 deposits of AuraBAL will be made in in Q1 2024, with a claimable date of 01-01-2025
      - 3 deposits of auraBAL will be made in Q2 2024, with a claimable date of 04-01-2025
      
- The contract has a a rage quit function
   - Requires Owner (maxis + dao)
   - Transfers all auraBAL in the contract to a specfied address

This will allow the maxis + the dao to handle upgrades or any issues.

**Comment by SHAKOTN** [comment]
I will start working on this next week and will create a repo asap

**Comment by SHAKOTN** [comment]
Moved ticket here:
https://github.com/BalancerMaxis/maxi-pay/issues/1
