### ISSUE TITLE
Practice on Injector Payload on Gnosis.

### ISSUE THREAD

**Issue by Zen-Maxi** [BalancerMaxis/multisig-ops#576]
This payload had sugar spice and a bit of everything nice in it. Gosuto has some insights on what needs to be done to get this job done as something different we face. The goal of the payload is as follows:

Further the Balancer Maxi’s are instructed to sweep all collected EURE/USDC fees earned as of October 15th to USDC a separate account. These fees will then be streamed as follows:

October 19th:
20% of total as direct incentives over the AURA platform on sDAI/EURe
20% of the total as direct incentives over the Balancer platform on sDAI/EURe

The remaining 60% of USDC will streamed in 2 weekly epochs extending from the end of the October 19th emissions.
Total USDC: 33,266.100194

Summary: We need the LM Multisig on Gnosis to accept ownership of the injector, set its recipient list to be the sDAI/EURE gauge for 2 pay periods each of which is 9979.830058 USDC. For this amount to be spent, we need to transfer 2x 9979.830058 USDC to the injector, and 6653.220039 to the Aura reward stash. We also will need the LM Multisig to approve the gauge as a spender of the 20% of direct incentives on Balancer. The gauge will need USDC added as a reward token with the distributor as the LM Multisig. Then the 20% we approved, can be deposited as a reward token. Lastly the LM Multisig needs to set_rewards_distributor as the injector for USDC on gnosis. This can all be one atomic payload. 

Some relevant addresses (on gnosis): sDAI/EURe gauge - 0xBB2598b89202596A743BE0b615001D7D5164f167 -- injector - 0x87c921be1fd8ee7E5eda4394aDB849DB72847aE9 -- Aura stash contract - 0x6068eb7490748A1A49830B58524C002b545c1Ce2 -- USDC address can be found on CG, LM Multisig and any other addresses needed on docs deployments page for Gnosis.

**Comment by gosuto-inzasheru** [comment]
started work on this but found out the actual tx got execd already, rendering onchain state difficult to use for building the payload: https://gnosisscan.io/tx/0x448c507bee9399ec4ac27472eb3a535000d6dc0c5cc83bbb3e50884323eaa268/

**Comment by Zen-Maxi** [comment]
no worries, next time one comes around we can have some fun in the complexity.
