### ISSUE TITLE
fix: hardcoded url points to 404

### ISSUE THREAD

**Issue by gosuto-inzasheru** [BalancerMaxis/multisig-ops#649]
@Tritium-VLK the `vault_permissions.md` file hardcoded here doesnt exist, where did it move to?

https://github.com/BalancerMaxis/multisig-ops/blob/70f869b2e74d785b698e4e3051154c126b7f6b4e/BIPs/00batched/authorizer/func_desc_by_name.json#L9-L14

**Comment by Tritium-VLK** [comment]
See #653

**Comment by gosuto-inzasheru** [comment]
this is not solved yet. please dont close prematurely.

**Comment by gosuto-inzasheru** [comment]
- [ ] urls in `func_desc_by_name.json` will need to be updated to point to `main` branch
- [ ] urls on forum for the [Wire Up Batch Relayer V6](https://forum.balancer.fi/t/rfc-wire-up-batch-relayer-v6/5358)](https://forum.balancer.fi/t/rfc-wire-up-batch-relayer-v6/5358) post will need updating
