### ISSUE TITLE
DAO vlAURA voting

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/multisig-ops#685]
We need to start voting with our vlAURA (before christmas really): https://forum.balancer.fi/t/bip-xxx-utilize-locked-aura-to-support-ecosystem-growth/5419

We will start by manually placing votes calculated on this [sheet](https://docs.google.com/spreadsheets/d/1vcbquSO28E7rfM92X1cUZ3nK1z59U5FTHMTuwGIIHTU/edit#gid=1793810576) and move towards integration.

In order to support the following objective we need data about earnings:
```
Revenue Producing Pools (40%)
40% of the vlAura will be used to vote for sustainable revenue producing pools. We define a sustainable revenue producing pool as a pool with predictable revenue production that does not depend on volatility to earn protocol revenue. This would be inclusive of major LST stableswap pools with fee on yield (Lido stETH, rocketpool rETH, frax sfrxETH) and pools with >=50% composition of major interest bearing stablecoin pools (sDAI, sFRAX).

The allocation strategy will be simple, first we will designate a list of pools to be considered as “core revenue producing pools” which align with the composition described above. This vote weight will be distributed pro-rata according to the revenue earned relative to other core revenue producing pools. So if pool A earns 30k, pool B earns 10k, and pool C earns 20k, the vote weight distribution will be 50,16.6, 33.3. In order to simplify voting and minimize dust amounts, we will initially restrict this to the top 6 pools.

These pools should not be used to further business development efforts and should solely be utilized to promote DAO revenue.
```

So we need a list of earnings per pool system wide, ordered by earnings.  This includes fees earned by all revenue sources (protocol fees, yield fees).  From this the Maxis can find the 6 pools for the above distributions.

**Comment by Tritium-VLK** [comment]
Asked Fabio about a dune dashboard.  Then maybe Gos + Mike can help to get a sheet together to determine voting.

**Comment by gosuto-inzasheru** [comment]
picking this up based on https://dune.com/queries/3293596

**Comment by gosuto-inzasheru** [comment]
in pr #691, "sustainable" pools are defined as having a pool type of stable or gyro, and having a rate provider (ie interest bearing).

table of top 6 sustainable pools can be generated based on any arbitrary time window.

i think next step would be to also automatically query the other 40% of the votes; the pools for the core liquidity
