### ISSUE TITLE
crossref core pools config file vs subgraph query of stable/gyro pool with rate provider

### ISSUE THREAD

**Issue by gosuto-inzasheru** [BalancerMaxis/multisig-ops#704]
i have the feeling there are some pools that are stable and have rate providers (ie interest bearing), but arent a core pool.

maybe on purpose, maybe not. needs to be evaluated and possibly automated.

@SHAKOTN i understood you are working on a similar task or not? any overlap?

i currently have a [query](https://github.com/BalancerMaxis/multisig-ops/blob/c1dd6bb49a03e7616bab88f0121acae53a15044a/tools/python/gen_vlaura_votes_for_epoch.py#L28-L62) in #691 which might come in handy :)

**Comment by SHAKOTN** [comment]
I believe we wanna do this in Q1: automatically identify core pools instead of just having a config file for that. But no, I am currently not working on that, it's the plan for the future

**Comment by Tritium-VLK** [comment]
This is being handled in: https://github.com/BalancerMaxis/bal_addresses/pull/177
