### ISSUE TITLE
Setup T token rewards on a few pools with Paladin as distributor

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/multisig-ops#751]
This is the distribution contract: 
Mainnet: 0xf0CeABf99Ddd591BbCC962596B228007eD4624Ae
Arbi: 0x8EdcFE9Bc7d2a735117B94C16456D8303777abbb
T token contract: 0xcdf7028ceab81fa0c6971208e83fa7872994bee5

And here are the pairs:
80T/20ETH: 0x8167a1117691f39e05e9131cfa88f0e3a620e96700020000000000000000038c
2BTC: 0xe4e72f872c4048925a78e1e6fddac411c9ae348a0000000000000000000005bc
Arbi wBTC / tBTC: 0xe4e72f872c4048925a78e1e6fddac411c9ae348a0000000000000000000005bc
Arbi tBTC/wETH:0xc9f52540976385a84bf416903e1ca3983c539e34000200000000000000000434

**Comment by Tritium-VLK** [comment]
![image](https://github.com/BalancerMaxis/multisig-ops/assets/11885129/d4728292-e532-4bb1-8c55-d56c0a8ba139)

**Comment by Tritium-VLK** [comment]
<img width="603" alt="image" src="https://github.com/BalancerMaxis/multisig-ops/assets/11885129/d3820e26-7282-40f9-9482-aacc41807423">

**Comment by Tritium-VLK** [comment]
<img width="613" alt="image" src="https://github.com/BalancerMaxis/multisig-ops/assets/11885129/1fc7978e-48b1-4426-a0d9-1e6158e8578a">

**Comment by Zen-Maxi** [comment]
Transaction for Arbotrum: https://app.safe.global/transactions/tx?id=multisig_0xc38c5f97B34E175FFd35407fc91a937300E33860_0xd0cb79d99ea445d5ed9bf3cb7987f5172b06450785ff3c1e465b8617fd1e2162&safe=arb1:0xc38c5f97B34E175FFd35407fc91a937300E33860 and for mainnet: https://app.safe.global/transactions/queue?safe=eth:0xc38c5f97B34E175FFd35407fc91a937300E33860
