### ISSUE TITLE
[Injector Request] rsETH pool on zkEVM

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/multisig-ops#769]
**What Chain/Pool?**
https://app.balancer.fi/#/zkevm/pool/0xffc865fcb34e754fad4b0144139b9c28c81c3eff00000000000000000000005f
**How many tokens for how long**
1500 USDC per week for 8 weeks
**When is this needed by?**
No deadline. 

**Current Balance of Injector**
https://injector-schedule.web.app/zkevm/0x2F1901f2A82fcC3Ee9010b809938816B3b06FA6A
The injector is currently empty with all current programs concluded.
**Additional context**
Requested by Jack Melnick from Polygon

**Comment by Zen-Maxi** [comment]
Took about 5x as long as actually queueing the txn for reference. At scale this does not work. https://github.com/BalancerMaxis/multisig-ops/pull/770 At

**Comment by Tritium-VLK** [comment]
Loaded and being handled in the slack sigops channel.
