### ISSUE TITLE
fix: not all rate providers are recognised by ci report

### ISSUE THREAD

**Issue by gosuto-inzasheru** [BalancerMaxis/multisig-ops#873]
eg see https://github.com/BalancerMaxis/multisig-ops/pull/852#issuecomment-2023863311

**Comment by gosuto-inzasheru** [comment]
same for https://github.com/BalancerMaxis/multisig-ops/pull/871#issuecomment-2023950654

**Comment by Tritium-VLK** [comment]
I think the issue is that these are gyroscope pools.  Maybe there is another call to get the rate provider or something.

**Comment by Tritium-VLK** [comment]
Question in gyro chat:

Quick question on these new Rehype pools as we're reviewing them for gauge additions.  Here is an example pool:

https://optimistic.etherscan.io/address/0x8bb826afc0ff7d2c034a2883f4c461ffd238e1c3#readContract

Unlike other Balancer pools, this contract does not have a getRateProviders function that returns an array, and instead rateProvider0 `and `rateProvider1.  Are these always 2 token pools.  Do they map to the tokens array returned from the vault for the pool where 0 is index 0 and 1 is index 1?
