### ISSUE TITLE
bug: Fix tenderly sims

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/multisig-ops#902]
In this RUN ID the reporting failed on tenderly sim:
https://github.com/BalancerMaxis/multisig-ops/actions/runs/8736442395/job/23971305867

In this PR I removed the tenderly sim functionatliy from the reports, and then ran again/everything worked.  I also successfully simmed one of the payloads in tenderly via safe:
https://github.com/BalancerMaxis/multisig-ops/pull/901. - see https://github.com/BalancerMaxis/multisig-ops/pull/901/commits/057b524b28378f859eba9ec982489c1c6d6058c3

Tenderly generation will be globally disabled once that BIP is merged.

**Comment by Tritium-VLK** [comment]
That PR was a few weeks old and the delta was messy.  Cleaned up here:
https://github.com/BalancerMaxis/multisig-ops/pull/903

**Comment by gosuto-inzasheru** [comment]
i pushed a commit to that pr that wraps the tenderly sim in a try except. global disabling seems a bit of an overreaction

**Comment by Tritium-VLK** [comment]
That's better but it still seems to be skipping a lot:

https://github.com/BalancerMaxis/multisig-ops/pull/903#issuecomment-2066322187

Also here: https://github.com/BalancerMaxis/multisig-ops/pull/904#issuecomment-2067778329

Was hoping to see the combined payload manually sim.
